apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_WORKLOAD_NAME}
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: profile
        image: ${K8S_REGISTRY_IMAGE}:${K8S_COMMIT_REF}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000