apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: profile
        image: profile:1
        imagePullPolicy: "Never"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: NodePort
  selector:
    app: profile-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001