# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongodb-secret
# data:
#   MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
# stringData:
#   MONGO_INITDB_ROOT_USERNAME: user
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: dXNlcg==
  password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
        env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongodb-secret
          #       key: username
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongodb-secret
          #       key: password
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: "admin"
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   value: "password"
          # - name: MONGO_INITDB_DATABASE
          #   value: admin
        volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30003

